url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "GZZ criterion" # the name of your site, e.g. ACME Corp.
description: "A True 3D Hoek-Brown criterion for rock mass"
