menu:
- {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
#- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

people:
- {name: 'Hehua Zhu', title: 'Distinguish Professor', department: 'Department of Geotechnical Engineering', institution: 'Tongji University', institution_address: '1239 Siping Road, Yangpu District, Shanghai 200092, China', phone: '+86 (021) 65985014', email: 'zhuhehua@tongji.edu.cn', office: 'Geotechnical Building 708', image: 'assets/img/Hehua_Zhu.jpg', url: 'hehua_zhu', link: 'https://geotec.tongji.edu.cn/zhh/main.psp'}
- {name: 'Lianyang Zhang', title: 'Professor', department: 'Department of Civil and Architectural Engineering and Mechanics', institution: 'University of Arizona', institution_address: '1209 E. Second St. Tucson, AZ 85721, United States', phone: '+1 (520) 626-0523', email: 'lyzhang@arizona.edu', office: 'Civil Engineering 207D', image: 'assets/img/Lianyang_Zhang.jpg', url: 'lianyang_zhang', link: 'https://caem.engineering.arizona.edu/faculty-staff/faculty/lianyang-zhang'}
- {name: 'Qi Zhang', title: 'Professor', department: 'School of Civil Engineering', institution: 'Southeast University', institution_address: 'No. 2, Southeast University Road, Jiangning District, Nanjing 211189, Jiangsu Province, China', phone: '', email: 'zhangqi@seu.edu.cn', office: 'Civil Science Building 1401', image: 'assets/img/Qi_Zhang.jpg', url: 'qi_zhang', link: 'https://civil.seu.edu.cn/zq_30679/list.htm#19'}
- {name: 'Wuqiang Cai', title: 'Associate Professor', department: 'College of Transportation', institution: 'Tongji University', institution_address: '1239 Siping Road, Yangpu District, Shanghai 200092, China', phone: '', email: 'caiwuqiang95@tongji.edu.cn', office: '', image: 'assets/img/Wuqiang_Cai.jpg', url: 'wuqiang_cai', website: 'https://tjjt.tongji.edu.cn/info/2863/11279.htm'}
- {name: 'Haohua Chen', title: 'Associate Professor', department: 'Department of Geotechnical Engineering', institution: 'Tongji University', institution_address: '1239 Siping Road, Yangpu District, Shanghai 200092, China', phone: '', email: 'haohuachen@tongji.edu.cn', office: 'Geotechnical Building 704', image: 'assets/img/Haohua_Chen.jpg', url: 'haohua_chen', link: 'https://geotec.tongji.edu.cn/chh/main.htm'}

#courses:
#- {name: 'Vector Calculus', url: 'vector-calculus'}
#- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
#- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/GZZmodel'}
- {icon: 'linkedin', link: ''}
#- {icon: 'wechat', link: ''}

contacts:
- {name: 'Dr. Chen', title: 'Associate Professor', department: 'Department of Geotechnical Engineering', institution: 'Tongji University', institution_address: '1239 Siping Road, Yangpu District, Shanghai 200092, China', phone: '', email: 'haohuachen@tongji.edu.cn', office: 'Geotechnical Building 704', image: 'assets/img/contact.jpg'}
